cloudtrust/keycloak-bridge

- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- internal/keycloakb/eventsdb.go
- pkg/event/instrumenting.go
- pkg/event/logging.go
- pkg/event/module.go
- pkg/event/tracing.go
Add module to persist Keycloak events in database.
> Persist events in BD - First stage

- Gopkg.lock
- Gopkg.toml
- api/management/api.go
- api/management/api_test.go
- api/management/swagger-api_management.yaml
- cmd/keycloakb/keycloak_bridge.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
- pkg/management/http.go
- pkg/management/mock/component.go
- pkg/management/mock/keycloak_client.go
- pkg/middleware/mock/management_component.go
Depends on cloudtrust/keycloak-client#5
> Add missings custom API calls (credentials management)

- pkg/management/component.go
- pkg/management/component_test.go
return error if issue happens while reading the configuration from the DB
> add management of DB failure while reading the configuration

- cmd/keycloakb/keycloak_bridge.go
There is some space for improvements and we will have to fix this issue in all our modules
> Remove leakage of sensitive information

- Gopkg.lock
- README.md
- api/management/api.go
- api/management/api_test.go
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- pkg/account/http.go
- pkg/events/http.go
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
- pkg/management/http.go
- pkg/management/http_test.go
Regular expressions are currently hard-coded in source code. We may consider to externalize it in configuration but I think we would need to do it once we have merged all common stuff as input validation is quite global and should be done globally in my opinion
> Input validation

- Gopkg.toml
- cmd/keycloakb/keycloak_bridge.go
Build will fail until cloudtrust/common-service#13 is merged
> Use flyway check feature from common-service

- Gopkg.lock
- Gopkg.toml
- api/events/swagger-api_events.yaml
- api/management/api.go
- api/management/api_test.go
- api/management/swagger-api_management.yaml
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
- pkg/management/http.go
This PR is related to:
* cloudtrust/keycloak-rest-api-extensions#14
* cloudtrust/keycloak-client#14
⚠️ Build can't be successful until cloudtrust/keycloak-client#14 is merged
> [CLOUDTRUST-1423] Support paging for GetUsers

- pkg/events/http.go
Notes:
* \w is any word character : letter, digit or underscore
* \d is a digit
> [CLOUDTRUST-1330] Parameter validation fails for 2ND_FACTOR_ENROLLED

- pkg/account/component.go
- pkg/account/component_test.go
Catch the error message when trying to update the password
> Invalid password message

- api/management/swagger-api_management.yaml
add reminder email API in swagger description of the bridge
> [CLOUDTRUST-1457] Swagger reminder email

- api/management/api.go
- api/management/api_test.go
- pkg/management/component.go
- pkg/management/component_test.go
Integrate changes from cloudtrust/keycloak-bridge#98
> [CT-1442 + 1476] Fix empty arrays serialization

- Gopkg.lock
- Gopkg.toml
- api/account/api.go
- api/account/swagger-api_account.yaml
- cmd/keycloakb/keycloak_bridge.go
- pkg/account/component.go
- pkg/account/component_test.go
- pkg/account/endpoint.go
- pkg/account/endpoint_test.go
- pkg/management/component.go
Needs an update of keycloka-client dependency before merge
> Cloudtrust 1617 update account

- Gopkg.lock
- Gopkg.toml
- api/account/swagger-api_account.yaml
- cmd/keycloakb/keycloak_bridge.go
- pkg/account/component.go
- pkg/account/component_test.go
- pkg/account/endpoint.go
- pkg/account/endpoint_test.go
Needs:
* cloudtrust/keycloak-rest-api-extensions#17
* cloudtrust/keycloak-client#21
> Self delete API

- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- pkg/event/http.go
- pkg/event/http_test.go
Also fix rate limiter configuration
> [CLOUDTRUST-1635] Log error for event endpoint

- Gopkg.lock
- Gopkg.toml
- README.md
- api/account/api.go
- api/account/api_test.go
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- pkg/account/component_test.go
Depends on:
common-service: cloudtrust/common-service#25
keycloak-client: cloudtrust/keycloak-client#26
> [CLOUDTRUST-1801] Support multiple OIDC verifier URL

- Gopkg.lock
- Gopkg.toml
- README.md
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- internal/keycloakb/configdbmodule.go
- internal/keycloakb/configdbmodule_test.go
- internal/keycloakb/eventsdbmodule.go
- internal/keycloakb/mock_test.go
- pkg/events/mock_test.go
- pkg/export/storage.go
Implement liveness probe
Feature implemented in cloudtrust/common-service#30
Feature referenced in cloudtrust/keycloak-client#34
Feature used by cloudtrust/keycloak-bridge#148
> [CLOUDTRUST-2064] Add liveness probe

- Gopkg.lock
- README.md
- api/register/api.go
- api/register/api_test.go
- api/register/swagger-api_register.yaml
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- internal/dto/configuration.go
- internal/keycloakb/mock_test.go
- internal/messages/errormessages.go
- pkg/register/authorization.go
- pkg/register/authorization_test.go
- pkg/register/component.go
- pkg/register/component_test.go
- pkg/register/endpoint.go
- pkg/register/endpoint_test.go
- pkg/register/http.go
- pkg/register/http_test.go
- pkg/register/mock_test.go
- pkg/register/module.go
- pkg/register/module_test.go
Uses cloudtrust/keycloak-client#37
> [CLOUDTRUST-2107] Add register API

- Gopkg.lock
- Gopkg.toml
- api/account/api.go
- api/account/swagger-api_account.yaml
- api/management/api.go
- api/management/api_test.go
- internal/keycloakb/configdbinstrumenting.go
- internal/keycloakb/configdbmodule.go
- pkg/account/component.go
- pkg/account/component_test.go
- pkg/kyc/mock_test.go
- pkg/management/component.go
- pkg/management/endpoint_test.go
- pkg/management/mock_test.go
- pkg/register/mock_test.go
- pkg/validation/mock_test.go
Needs cloudtrust/common-service#42
> [CLOUDTRUST-2320] Use default value for admin conf. Validation enhancements

- Gopkg.lock
- Gopkg.toml
- api/management/swagger-api_management.yaml
- cmd/keycloakb/keycloak_bridge.go
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
- pkg/management/mock_test.go
Uses cloudtrust/keycloak-client#53
> [CLOUDTRUST-2402] Add methods to make a user join/leave a group

- pkg/event/component.go
The almost smallest PR you ever reviewed !!!!
> [CLOUDTRUST-2283] EMAIL_CONFIRMED event missing

- Gopkg.lock
- Gopkg.toml
- api/account/api.go
- api/account/api_test.go
- api/events/api.go
- api/events/api_test.go
- api/kyc/api.go
- api/management/api.go
- api/management/api_test.go
- api/statistics/api.go
- api/statistics/api_test.go
- api/validation/api.go
- api/validation/api_test.go
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- internal/keycloakb/accreditationsmodule.go
- internal/keycloakb/accreditationsmodule_test.go
- internal/keycloakb/kcauthclient.go
- internal/keycloakb/kcauthclient_test.go
- pkg/account/component_test.go
- pkg/kyc/component.go
- pkg/kyc/component_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/register/component.go
- pkg/register/component_test.go
- pkg/register/mock_test.go
- pkg/validation/component.go
> [CLOUDTRUST-2506] Avoid panic when no-op database is used

- internal/keycloakb/usersdbmodule.go
The world's shortest PR you ever reviewed !!!
> [CLOUDTRUST-2607] Fix date of checks issue

- Gopkg.lock
- Gopkg.toml
- api/register/api.go
- api/register/api_test.go
- internal/constants/regexp.go
Needs cloudtrust/common-service#51
> [CLOUDTRUST-2642] Update the way birth location is validated

- Gopkg.lock
- Gopkg.toml
- cmd/keycloakb/keycloak_bridge.go
- internal/keycloakb/configdbmodule.go
- pkg/events/authorization.go
- pkg/events/authorization_test.go
- pkg/kyc/authorization.go
- pkg/kyc/authorization_test.go
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/statistics/authorization.go
- pkg/statistics/authorization_test.go
Linked to:
* cloudtrust/common-service#53
> [CLOUDTRUST-2432] /rights endpoint only returns the rights from bridge

- Gopkg.lock
- Gopkg.toml
- api/account/api.go
- api/account/swagger-api_account.yaml
- api/management/api.go
- api/management/swagger-api_management.yaml
- cmd/keycloakb/keycloak_bridge.go
- internal/constants/errormessages.go
- internal/keycloakb/mock_test.go
- internal/keycloakb/usersdbmodule.go
- internal/keycloakb/usersdbmodule_test.go
- pkg/account/component.go
- pkg/account/component_test.go
- pkg/management/component.go
- pkg/validation/component.go
Requires:
* cloudtrust/common-service#57
* cloudtrust/keycloak-client#64
> [CLOUDTRUST-2691] Add barcode type in realm configuration

- Gopkg.lock
- Gopkg.toml
- api/register/api.go
- api/register/api_test.go
- api/register/swagger-api_register.yaml
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- internal/keycloakb/configdbinstrumenting.go
- internal/keycloakb/configdbinstrumenting_test.go
- internal/keycloakb/configdbmodule.go
- internal/keycloakb/configdbmodule_test.go
- pkg/register/authorization.go
- pkg/register/authorization_test.go
- pkg/register/component.go
- pkg/register/component_test.go
- pkg/register/endpoint.go
- pkg/register/endpoint_test.go
- pkg/register/http.go
- pkg/register/http_test.go
Requires:
* cloudtrust/common-service#62
* cloudtrust/keycloak-client#70
> [CLOUDTRUST-2805] Support multiple realms for register interface

- README.md
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- internal/dto/archive.go
- internal/dto/archive_test.go
- internal/keycloakb/archivedbmodule.go
- internal/keycloakb/archivedbmodule_test.go
- pkg/kyc/component.go
- pkg/kyc/component_test.go
- pkg/kyc/mock_test.go
- pkg/validation/component.go
- pkg/validation/component_test.go
- pkg/validation/endpoint_test.go
- pkg/validation/mock_test.go
If this PR is merged after cloudtrust/keycloak-bridge#247, IDDocumentCountry might be added to archived fields
> [CLOUDTRUST-2777] Users archiving

- Gopkg.lock
- Gopkg.toml
- api/communications/api.go
- api/communications/api_test.go
- api/communications/swagger-api_communcations.yaml
- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- pkg/communications/authorization.go
- pkg/communications/authorization_test.go
- pkg/communications/component.go
- pkg/communications/component_test.go
- pkg/communications/endpoint.go
- pkg/communications/endpoint_test.go
- pkg/communications/http.go
- pkg/communications/http_test.go
- pkg/communications/mock_test.go
- pkg/management/component.go
- pkg/management/component_test.go
This implelents the COM stack for the CPR project. It should be merged at the same time like https://github.com/cloudtrust/keycloak-client/pull/73.
> [SCRP-32] Communication API

- internal/keycloakb/datehelpers.go
- internal/keycloakb/mfa_tools.go
- internal/keycloakb/mfa_tools_test.go
- internal/keycloakb/pii.go
- pkg/account/component.go
- pkg/account/component_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/mock_test.go
> [CLOUDTRUST-2169] Prevent removal of last MFA credential

- api/account/api.go
- api/communications/api.go
- api/kyc/api.go
- api/management/api.go
- api/register/api.go
- api/validation/api.go
- internal/constants/regexp.go
- pkg/account/http.go
- pkg/management/http.go
- pkg/validation/http.go
There are remaining inconsistencies in first name/last name usages of regex we shall discuss
> [CLOUDTRUST-3217] Use same regex checks between interfaces

- Gopkg.lock
- Gopkg.toml
- api/management/swagger-api_management.yaml
- cmd/keycloakb/keycloak_bridge.go
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
Needs cloudtrust/keycloak-client#90
> [CLOUDTRUST-3403] Add functions to manage user roles

- api/account/api_test.go
- api/management/api.go
- internal/constants/regexp.go
Reverts cloudtrust/keycloak-bridge#351
> Revert "[CLOUDTRUST-2759] Update regex for username"

- api/account/api.go
- api/account/swagger-api_account.yaml
- api/management/api.go
- api/management/api_test.go
- api/management/swagger-api_management.yaml
- go.mod
- go.sum
- internal/constants/errormessages.go
- pkg/account/component.go
- pkg/management/component.go
- vendor/modules.txt
Dependency not yet added for changes in common-services
> [CLOUDTRUST-3931] Allow definition of SSE default tab

- api/management/swagger-api_management.yaml
- cmd/keycloakb/keycloak_bridge.go
- go.mod
- go.sum
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- vendor/modules.txt
Need to update keycloak-client dependency
> [CLOUDTRUST-3995] Add management API method to update a role

- api/account/api.go
- pkg/management/component_test.go
Also added unit tests for isEmailVerified/isPhoneNumberVerified
> [CLOUDTRUST-5075] BusinessID seen to be removed on account update

- api/management/swagger-api_management.yaml
- api/register/swagger-api_register.yaml
We forgot to update the swaggers when we added the onboarding status
> [CLOUDTRUST-5540] Add onboarding status in swaggers
