cloudtrust/keycloak-bridge

- cmd/keycloakb/keycloak_bridge.go
- configs/keycloak_bridge.yml
- pkg/event/module.go
- pkg/export/storage.go
- pkg/management/module.go
- pkg/management/module_test.go
Check that the minimum required database schema version is deployed when starting the component (bridge and alerting components). If this is not the case, then the component is stopped with an appropriate error log.
The configuration must also contain a flag, whether to check or not this minimum version. The purpose of this flag is to ignore this check if flyway is not yet used for setting up the database (do not even check whether the table flyway_schema_history exists).
> Db migration

- Gopkg.lock
- pkg/account/component.go
- pkg/event/component.go
- pkg/event/component_test.go
- pkg/management/component.go
(build will fail until cloudtrust/common-service#15 is merged)
> Use constants for columns in events management

- configs/keycloak_bridge.yml
each DB connection must have its min version, if applicable
> CLOUDTRUST-1004: fix default configuration (min dbschema version)

- cmd/keycloakb/keycloak_bridge.go
- configs/authorization.json
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
Add the new "send onboarding reminder mail" API in the bridge.
At the authorization level: SendReminderEmail is similar to SendVerifyEmail; to be decided if this will stay like this
> Send reminder email

- configs/authorization.json
People who have ExecuteActionsEmail rights need GetRealmCustomConfiguration as well.
Or else, they are not able to read the redirectUri when trying to trigger an Required Actions email...
> CLOUDTRUST-1356 

- api/management/swagger-api_management.yaml
- configs/authorization.json
- internal/keycloakb/passwordgeneration.go
- internal/keycloakb/passwordgeneration_test.go
- pkg/management/authorization.go
- pkg/management/authorization_test.go
- pkg/management/component.go
- pkg/management/component_test.go
- pkg/management/endpoint.go
- pkg/management/endpoint_test.go
- pkg/management/http_test.go
adapt the exisiting reset-password endpoint to generate a random password if no value is provided in the request.
The generated value will be returned in the content of the response (JSON structure).
The randomly generated password must comply with the password policy defined in the target realm.
> [CLOUDTRUST-1504] reset password

- configs/keycloak_bridge.yml
- pkg/event/component.go
Due to an issue with MariaDB reported by SSO, usage of time_zone=UTC in DB connection string leads to some issues in their side. 
We change to use system locale and we now need to assume Locale of Db and Bridge are aligned.
> Cloudtrust 1771 fix timezone

- configs/keycloak_bridge.yml
- pkg/event/component.go
- pkg/event/component_test.go
One of the unittests was failing in our local CI.
I think Travis locale is UTC so it was not detected here.
> Cloudtrust 1771 fix unittest

- pkg/management/component.go
- pkg/management/component_test.go
if a credential other than the password was deleted, record the event 2ND_FACTOR_REMOVED in the audit DB
> [CLOUDTRUST-1713] record 2ND_FACTOR_REMOVED event

- cmd/keycloakb/keycloak_bridge.go
- internal/keycloakb/configdbmodule.go
- internal/keycloakb/errormessages.go
- pkg/account/component.go
- pkg/management/component.go
- pkg/management/component_test.go
return a 404 with message when realmconfig is not configured; before it was a 500
> [CLOUDTRUST-1875] Return error with message when Realm config is not configured

- Jenkinsfile
With an old version of curl (7.29 in our case), and when pushing our release to a tls-enabled server, it happens that the certificate is treated to be invalid even if the hostname is explicitely written in the Subject Alternative Name as a DNS name.
The common fix is just to pass curl -k and bypass the certificate validation, sadly.
> [CLOUDTRUST-1898] Support making releases through https.

- Jenkinsfile
The -noColor option of nancy got deprecated in v0.0.29. Instead, it got replaced by -no-color.
> Fix deprecated nancy colouring option.

- Gopkg.lock
- Gopkg.toml
- api/kyc/swagger-api_kyc.yaml
- cmd/keycloakb/keycloak_bridge.go
- pkg/kyc/authorization.go
- pkg/kyc/authorization_test.go
- pkg/kyc/component.go
- pkg/kyc/component_test.go
- pkg/kyc/endpoint.go
- pkg/kyc/endpoint_test.go
- pkg/kyc/http.go
Coverage should decrease but I don't want to write unit tests for deprecated methods that will be removed soon.
> [CLOUDTRUST-2264] Add GetUser (by id) in kyc API

- cmd/keycloakb/keycloak_bridge.go
- internal/keycloakb/kcauthclient.go
- internal/keycloakb/kcauthclient_test.go
Needs cloudtrust/common-service#41
> [CLOUDTRUST-2375] Prevent access to KYC API when features are disabled

- api/account/api.go
- api/account/api_test.go
- api/account/swagger-api_account.yaml
- api/kyc/api.go
- api/kyc/api_test.go
- api/kyc/swagger-api_kyc.yaml
- api/management/api.go
- api/management/api_test.go
- api/management/swagger-api_management.yaml
- api/validation/api.go
- api/validation/api_test.go
- cmd/keycloakb/keycloak_bridge.go
- internal/constants/keycloak.go
- internal/keycloakb/accreditationsmodule.go
- internal/keycloakb/accreditationsmodule_test.go
- internal/keycloakb/datehelpers.go
- internal/keycloakb/datehelpers_test.go
- internal/keycloakb/mock_test.go
- pkg/kyc/component.go
- pkg/kyc/component_test.go
- pkg/kyc/mock_test.go
- pkg/statistics/component_test.go
- pkg/validation/component.go
- pkg/validation/component_test.go
- pkg/validation/mock_test.go
User accreditations are updated in /kyc and /validation
Accreditations are sent through the "GetUser" API of /kyc, /management and /users
> [CLOUDTRUST-2297] Add flag for user accreditations

- configs/keycloak_bridge.yml
These headers are needed to tell IE11 that he should NOT cache AJAX requests...
> CLOUDTRUST-2378 AJAX headers

- internal/keycloakb/eventsdbmodule.go
- internal/keycloakb/eventsdbmodule_test.go
Rewrite GetEvents query to avoid things like `(? IS NULL OR origin = ?)` and have only comparisons with constants.
This rewriting of requests should be easier to identity which indexes are required.
> [CLOUDTRUST-2807] GetEvents enhancements for performances

- api/register/swagger-api_register.yaml
- internal/constants/errormessages.go
- pkg/register/authorization.go
- pkg/register/authorization_test.go
- pkg/register/component.go
- pkg/register/component_test.go
- pkg/register/endpoint.go
- pkg/register/endpoint_test.go
I choosed to return a random username... but we can choose to return a constant username (ex: 00000000) or the actual username. Every solution leaks an information. We also can choose to stop returning the username which is not used by our front-end (but can be used by other GUI).
> [CLOUDTRUST-3408] Don't leak information that email already exists on registering

- internal/constants/regexp.go
- pkg/management/http.go
- pkg/management/http_test.go
Keycloak-bridge used to deny and return an invalid parameter error if we search for usernames, first/last names, or emails that do not satisfy a RegExp. This is not the behavior we intend as it may be useful to search for an address containing a substring.
> [CLOUDTRUST-5515] Allow more inputs for advanced search

- api/configuration/swagger-api_configuration.yaml
- pkg/configuration/component.go
- pkg/configuration/component_test.go
I also fixed the swagger and the errors being thrown to fit what we wanted.
> [CLOUDTRUST-5782] Make identification URI endpoint return an error for an empty URI

- pkg/management/component.go
- pkg/management/component_test.go
Added in Management API as usually done with other internal APIs (Tasks, Communications). A future JIRA will look into ways to improve this handling
> [CLOUDTRUST-6419] Add authz of IDP API to GetActions of Management API
